import AnonymousUser from "../models/anonymousUser.js";
import crypto from 'crypto';

// Helper to hash IP
const hashIp = (ip) => {
  return crypto.createHash('sha256').update(ip || 'unknown').digest('hex');
};

export const initializeAnonymousUser = async (req, res) => {
  try {
    const { 
      fbclid, 
      utm_source, 
      utm_medium, 
      utm_campaign, 
      utm_adset, 
      utm_ad, 
      landing_page, 
      referrer,
      device_info 
    } = req.body;

    const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress;
    const userAgent = req.headers['user-agent'];

    // Create new user - anon_id will be auto-generated by the model default
    const newUser = new AnonymousUser({
      first_seen_at: new Date(),
      last_seen_at: new Date(),
      acquisition: {
        source: fbclid ? 'meta' : (utm_source || 'direct'),
        fbclid,
        utm_source,
        utm_medium,
        utm_campaign,
        utm_adset,
        utm_ad,
        landing_page,
        referrer
      },
      device: {
        ip_hash: hashIp(ip),
        user_agent: userAgent,
        platform: device_info?.platform || 'unknown',
        screen_width: device_info?.screen_width,
        screen_height: device_info?.screen_height
      }
    });

    await newUser.save();

    // Set HTTP-only cookie
    res.cookie('anon_user_id', newUser.anon_id, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 365 * 24 * 60 * 60 * 1000 // 1 year
    });

    res.status(201).json({
      success: true,
      anon_user_id: newUser.anon_id,
      message: "Anonymous user initialized"
    });

  } catch (error) {
    console.error("Error initializing anonymous user:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};

export const updateAnonymousUserActivity = async (req, res) => {
    try {
        const { anon_user_id } = req.params;
        if (!anon_user_id) return res.status(400).json({ error: "ID required" });

        await AnonymousUser.findOneAndUpdate({ anon_id: anon_user_id }, {
            last_seen_at: new Date()
        });

        res.status(200).json({ success: true });
    } catch (error) {
        console.error("Error updating anonymous user:", error);
        res.status(500).json({ error: "Internal server error" });
    }
};
