import EventManager from "../models/eventManager.js";
import EMNotifications from "../models/emNotifications.js";
import SalesExecutive from "../models/salesExecutive.js";
import BusinessAdmin from "../models/businessAdmin.js";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";

const JWT_SECRET = process.env.JWT_SECRET;

/**
 * Authenticate EM admin user
 */
export const authenticateEMAdmin = async (req, res) => {
  const { user_name, password } = req.body;

  // Input validation: check if username and password are provided
  if (!user_name || !password) {
    return res
      .status(400)
      .json({ success: false, message: "Username and password are required" });
  }

  try {
    // 1️⃣ Find user by username (case-insensitive)
    const user = await EventManager.findOne({
      user_name: { $regex: new RegExp(`^${user_name}$`, "i") },
    });

    if (!user) {
      return res.status(404).json({
        success: false,
        message: "User not found",
      });
    }

    // 2️⃣ Verify password
    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      return res.status(401).json({
        success: false,
        message: "Invalid credentials",
      });
    }

    // 3️⃣ Generate JWT
    const token = jwt.sign(
      {
        em_id: user.em_id,
        user_name: user.user_name,
        contact_name: user.contact_name,
        role: "rmadmin",
      },
      JWT_SECRET,
    );

    // 4️⃣ Return token + user info
    return res.status(200).json({
      success: true,
      message: "Authenticated successfully",
      token,
      user: {
        em_id: user.em_id,
        user_name: user.user_name,
        contact_name: user.contact_name,
      },
    });
  } catch (err) {
    console.error("Auth error:", err);
    return res.status(500).json({
      success: false,
      message: "Internal server error",
    });
  }
};

/**
 * Authenticate Sales Admin user
 */
export const authenticateSalesAdmin = async (req, res) => {
  const { user_name, password } = req.body;

  // Input validation
  if (!user_name || !password) {
    return res
      .status(400)
      .json({ success: false, message: "Username and password are required" });
  }

  try {
    // 0️⃣ Check if SalesExecutive collection is empty and create default user if so
    const count = await SalesExecutive.countDocuments();
    if (count === 0) {
      console.log(
        "SalesExecutive collection is empty. Creating default user...",
      );
      const salt = await bcrypt.genSalt(10);
      const hashedPassword = await bcrypt.hash("sales", salt);

      await SalesExecutive.create({
        user_name: "sales",
        password: hashedPassword,
        contact_name: "Sales Admin",
        // sales_ex_id will be auto-generated by default function in model
      });
      console.log("Default sales user created: sales/sales");
    }

    // 1️⃣ Find user by username
    const user = await SalesExecutive.findOne({ user_name });

    if (!user) {
      return res.status(404).json({
        success: false,
        message: "User not found",
      });
    }

    // 2️⃣ Verify password
    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      return res.status(401).json({
        success: false,
        message: "Invalid credentials",
      });
    }

    // 3️⃣ Generate JWT
    const token = jwt.sign(
      {
        sales_ex_id: user.sales_ex_id,
        user_name: user.user_name,
        contact_name: user.contact_name,
        role: "sales_admin",
      },
      JWT_SECRET,
    );

    // 4️⃣ Return token + user info
    return res.status(200).json({
      success: true,
      message: "Authenticated successfully",
      token,
      user: {
        sales_ex_id: user.sales_ex_id,
        user_name: user.user_name,
        contact_name: user.contact_name,
      },
    });
  } catch (err) {
    console.error("Sales Auth error:", err);
    return res.status(500).json({
      success: false,
      message: "Internal server error",
    });
  }
};

/**
 * Authenticate Business Admin user (plain-text password match)
 */
export const authenticateBusinessAdmin = async (req, res) => {
  const { user_name, password } = req.body;

  if (!user_name || !password) {
    return res
      .status(400)
      .json({ success: false, message: "Username and password are required" });
  }

  try {
    const user = await BusinessAdmin.findOne({
      user_name: { $regex: new RegExp(`^${user_name}$`, "i") },
    });

    if (!user) {
      return res
        .status(404)
        .json({ success: false, message: "User not found" });
    }

    // Plain-text comparison
    if (user.password !== password) {
      return res
        .status(401)
        .json({ success: false, message: "Invalid credentials" });
    }

    const token = jwt.sign(
      {
        business_admin_id: user.business_admin_id,
        user_name: user.user_name,
        contact_name: user.contact_name,
        role: "business",
      },
      JWT_SECRET,
    );

    return res.status(200).json({
      success: true,
      message: "Authenticated successfully",
      token,
      user: {
        business_admin_id: user.business_admin_id,
        user_name: user.user_name,
        contact_name: user.contact_name,
        role: "business",
      },
    });
  } catch (err) {
    console.error("Business Admin Auth error:", err);
    return res
      .status(500)
      .json({ success: false, message: "Internal server error" });
  }
};

/**
 * Get notifications for an admin
 */
export const getEMNotifications = async (req, res) => {
  const { em_id } = req.params;

  try {
    if (!em_id) {
      return res.status(400).json({
        success: false,
        message: "em_id is required",
      });
    }

    const notifications = await EMNotifications.find({ em_id }).sort({
      timestamp: -1,
    });

    return res.status(200).json({
      success: true,
      data: notifications,
    });
  } catch (error) {
    console.error("Error fetching notifications:", error);
    return res.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
};

/**
 * Mark all unread notifications as read
 */
export const markAllNotificationsAsRead = async (req, res) => {
  const { em_id } = req.body;

  if (!em_id) {
    return res.status(400).json({ message: "em_id is required" });
  }

  try {
    await EMNotifications.updateMany(
      { em_id: em_id, read: false },
      { $set: { read: true } },
    );

    return res.status(200).json({ success: true, message: "Marked as read" });
  } catch (err) {
    console.error("Failed to mark notifications as read:", err);
    return res.status(500).json({ success: false, message: "Server error" });
  }
};

/**
 * Get Event Manager Profile
 */
export const getEMProfile = async (req, res) => {
  try {
    const { em_id } = req.params;
    if (!em_id) {
      return res
        .status(400)
        .json({ success: false, message: "em_id required" });
    }

    const profile = await EventManager.findOne({ em_id }).select("-password");
    if (!profile) {
      return res
        .status(404)
        .json({ success: false, message: "Profile not found" });
    }

    return res.status(200).json({
      success: true,
      data: profile,
    });
  } catch (error) {
    console.error("Error fetching EM profile:", error);
    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

/**
 * Update Event Manager Profile
 */
export const updateEMProfile = async (req, res) => {
  try {
    const { em_id } = req.params;
    const updates = req.body;

    if (!em_id) {
      return res
        .status(400)
        .json({ success: false, message: "em_id required" });
    }

    // Prevent password or em_id modification
    delete updates.password;
    delete updates.em_id;

    const updatedProfile = await EventManager.findOneAndUpdate(
      { em_id },
      { $set: updates },
      { new: true, runValidators: true },
    ).select("-password");

    if (!updatedProfile) {
      return res
        .status(404)
        .json({ success: false, message: "Profile not found" });
    }

    return res.status(200).json({
      success: true,
      message: "Profile updated successfully",
      data: updatedProfile,
    });
  } catch (error) {
    console.error("Error updating EM profile:", error);
    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};

/**
 * Get list of all Event Managers
 */
export const getAllEMs = async (req, res) => {
  try {
    const ems = await EventManager.find(
      {},
      "em_id contact_name user_name email phone profile_pic"
    ).lean();

    return res.status(200).json({
      success: true,
      data: ems,
    });
  } catch (error) {
    console.error("Error fetching EM list:", error);
    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
};
